#!/usr/bin/env bash
# A script

sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
sudo service nginx reload
