#!/usr/bin/env bash
#install haproxy on a server

# Enable a dedicated PPA 
sudo apt-get -y update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8

# Install Haproxy
sudo apt-get -y install haproxy=2.8.\*

# Getting access privileges to config
sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg old_haproxy_cfg

echo "global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

# Default section
defaults 0x0f
    mode http

# Frontend section
frontend website from 0x0f
    bind *:80
    default_backend web_servers

# Backend section
backend web_servers from 0x0f
    balance roundrobin
    server s1 34.203.77.10:80 check
    server s2 35.153.93.177:80 check" > /etc/haproxy/haproxy.cfg

# Restart Haproxy
sudo service haproxy restart
