#!/usr/bin/env bash
#install haproxy on a server

# Enable a dedicated PPA 
sudo apt-get -y update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8

# Install Haproxy
sudo apt-get -y install haproxy=2.8.\*

# Getting access privileges to config
sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg old_haproxy_cfg
echo "ENABLED=1" > /etc/default/haproxy

echo "
listen myserver
	bind *:80
	balance roundrobin
    server web1 34.203.77.10:80 check
    server web2 35.153.93.177:80 check" >> /etc/haproxy/haproxy.cfg

# Restart Haproxy
sudo service haproxy restart
