#!/usr/bin/env bash
# a Bash script that displays Best School 10 times.

i=1

while ((i<=100));
do
	if ((i%3 == 0)) && ((i%5 == 0));
	then
		echo "FizzBuzz"
		((i++))
		continue
	elif ((i%3 == 0));
	then
		echo "Fizz"
	elif ((i%5 == 0))
	then
		echo "Buzz"
	else
		echo $i
	fi
	(( i++ ))
done
