#!/usr/bin/env bash
# a Bash script that displays Best School 10 times.

i=1

while ((i<=10));
do
	if ((i == 9));
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	(( i++ ))
done
