#!/usr/bin/env bash
# a Bash script that displays Best School 10 times.

h=1
m=1
echo "Hour: 0"
while ((h<=13))
do
	echo $m
	if((m == 59))
	then
		if((h == 13))
		then
			break
		else
			echo "Hour: "$h
			((m=0))
			((h++))
		fi
	fi
	((m++))
done
